### ISSUE TITLE
semantic versioning problem

### ISSUE THREAD

**Issue by matkoniecz** [rdp/os#26]
If this gem is not following semantic versioning - please ignore and close this issue.

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

http://semver.org/

So I would consider bumping version to 1.something.something (currently it is `"0.10.0"`).

**Comment by rdp** [comment]
OK, was this auto generated comment, or a request from a human??

On Fri, Feb 10, 2017 at 2:58 AM, Mateusz Konieczny <notifications@github.com

**Comment by matkoniecz** [comment]
This issue is 1000% handmade by a human.

I noticed it on committing Gemfile.lock file in project that is using this gem.

**Comment by rdp** [comment]
Awesome, I'll go ahead and bump it to version 1.0, my first project to even
be declared that way I believe LOL.
-roger-

On Fri, Feb 10, 2017 at 8:04 AM, Mateusz Konieczny <notifications@github.com

**Comment by rdp** [comment]
bumped it, thanks for your contrib.

**Comment by matkoniecz** [comment]
Thanks!
