### ISSUE TITLE
detect OS sleep state

### ISSUE THREAD

**Issue by bigbgh** [rdp/os#35]
Feature request - detect when the OS is sleeping and waking. My particular interest is on macOS.

**Comment by rdp** [comment]
So you want like a callback when the computer goes to sleep?  Hmm that
might require some ffi magic...

**Comment by bigbgh** [comment]
The use case I had in mind was the BitBar WorkTime plugin...because I
usually forget to stop or pause before shutting my laptop. I thought it
would be great to auto pause when it gets the sleep signal upon shutting
the lid. However, now I'm thinking an easier approach might be to just
start a timer and that should automatically stop when it goes to sleep.
Haven't got a chance to test it yet.

**Comment by bigbgh** [comment]
Started using Toggl.
