### ISSUE TITLE
Provide tag for version 1.0.1

### ISSUE THREAD

**Issue by koppor** [rdp/os#36]
Version 1.0.1 is released: https://rubygems.org/gems/os

I don't see a 1.0.1 tag in this repository. Is this intended?

Maybe, you could use [KeepAChangelog](https://keepachangelog.com/en/1.0.0/) instead of the custom log format (https://github.com/rdp/os/blob/master/ChangeLog). 😇

**Comment by rdp** [comment]
Hmm making a tag for every release seems like overkill for such a small
project hmm :)

**Comment by koppor** [comment]
I think all projects deserve proper versioning 😇. If something goes wrong while using, it is more easy to report issues (or even track down), if the concrete code for a concrete version is known.

**Comment by shepmaster** [comment]
> for such a small project

Your project is used by the [googleauth](https://rubygems.org/gems/googleauth) gem, which seems likely to be used by a fair number of projects.

**Comment by rdp** [comment]
I think 1.1 is tagged right...FWIW :)

**Comment by koppor** [comment]
Thank you!

In case you are afraid of the effort, you can use https://www.npmjs.com/package/github-release-from-changelog. OK, then the issue is to switch from a custom changelog format (https://github.com/rdp/os/blob/master/ChangeLog) to [KeepAChangelog](https://keepachangelog.com/en/1.0.0/). ^^

**Comment by shepmaster** [comment]
> I think 1.1 is tagged right

It might be, but I stumbled on this issue when attempting to figure out what had changed from 1.0.1 to 1.1. ([This was the best I could figure](https://github.com/rdp/os/compare/bc1a7c20a53e402f24b81eedceb2c673fa2d6465..master))
