### ISSUE TITLE
missing git tag 1.1.4 

### ISSUE THREAD

**Issue by anthraxx** [rdp/os#66]
I'd like to ask to get tag for gem release 1.1.4 tagged and released. Not sure which commit, maybe f1f4c332048308d14160e33cc97a4214a368c9ee?

Reasoning:
It's not just important that it is easy to map tags to actual releases in the source tree. But for distro packaging we actually require to have a matching git tag for every release as the rule of thumb is to build from the version control state in order to aid transparency and confidence in public reviewed code etc.

Problem:
As of the above, the missing tag for 1.1.4 create the issue for me that i can't package ruby-os for our Distro currently.

Related to #36

**Comment by rdp** [comment]
attempted it

**Comment by anthraxx** [comment]
I believe it looks good, thank you very much :cat:
