### ISSUE TITLE
Speed up gem boot

### ISSUE THREAD

**Issue by mperham** [rdp/os#76]
This gem only needs `yaml` for the `OS.report` method. Most users aren't using this method. Could you move the `require "yaml"` line inside the report method so the gem boots much faster?

https://github.com/rdp/os/blob/9ee80f9ec0f59ecc731ecdc7c2a8f88180e385f5/lib/os.rb#L3

**Comment by mperham** [comment]
As an example, derailed shows that 100% of the allocated memory from this gem is due directly to requiring YAML.

```
    os: 0.6875 MiB
      yaml: 0.6875 MiB
        psych: 0.6875 MiB
```

**Comment by rdp** [comment]
I want to fix this, PR welcome as well :)
